import { PlayerFormData } from "../types";

const FormInitialData: PlayerFormData = Object.freeze({
  userId: null,
  userName: '',
  power: null,
  faction: '',
  timeZone: '',
  t1InfantryCount: 0,
  t2InfantryCount: 0,
  t3InfantryCount: 0,
  t4InfantryCount: 0,
  t5InfantryCount: 0,
  t1MagesCount: 0,
  t2MagesCount: 0,
  t3MagesCount: 0,
  t4MagesCount: 0,
  t5MagesCount: 0,
  t1ArchersCount: 0,
  t2ArchersCount: 0,
  t3ArchersCount: 0,
  t4ArchersCount: 0,
  t5ArchersCount: 0,
  t1CavalryCount: 0,
  t2CavalryCount: 0,
  t3CavalryCount: 0,
  t4CavalryCount: 0,
  t5CavalryCount: 0,
  t1FlyingCount: 0,
  t2FlyingCount: 0,
  t3FlyingCount: 0,
  t4FlyingCount: 0,
  t5FlyingCount: 0,
});

export default FormInitialData;